// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mysqlx_session.proto

package mysqlx_session

/*
Messages to manage Sessions

.. uml::

  == session start ==
  Client -> Server: AuthenticateStart
  opt
  Server --> Client: AuthenticateContinue
  Client --> Server: AuthenticateContinue
  end
  alt
  Server --> Client: AuthenticateOk
  else
  Server --> Client: Error
  end
  ...
  == session reset ==
  Client -> Server: Reset
  Server --> Client: Ok
  == session end ==
  Client -> Server: Close
  Server --> Client: Ok

*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/renthraysk/mysqlx/protobuf/mysqlx"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// the initial message send from the client to the server to start the
// authentication proccess
//
// :param mech_name: authentication mechanism name
// :param auth_data: authentication data
// :param initial_response: initial response
// :Returns: :protobuf:msg:`Mysqlx.Session::AuthenticateContinue`
type AuthenticateStart struct {
	MechName             *string  `protobuf:"bytes,1,req,name=mech_name,json=mechName" json:"mech_name,omitempty"`
	AuthData             []byte   `protobuf:"bytes,2,opt,name=auth_data,json=authData" json:"auth_data,omitempty"`
	InitialResponse      []byte   `protobuf:"bytes,3,opt,name=initial_response,json=initialResponse" json:"initial_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateStart) Reset()         { *m = AuthenticateStart{} }
func (m *AuthenticateStart) String() string { return proto.CompactTextString(m) }
func (*AuthenticateStart) ProtoMessage()    {}
func (*AuthenticateStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_mysqlx_session_47565295436dd474, []int{0}
}
func (m *AuthenticateStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateStart.Unmarshal(m, b)
}
func (m *AuthenticateStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateStart.Marshal(b, m, deterministic)
}
func (dst *AuthenticateStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateStart.Merge(dst, src)
}
func (m *AuthenticateStart) XXX_Size() int {
	return xxx_messageInfo_AuthenticateStart.Size(m)
}
func (m *AuthenticateStart) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateStart.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateStart proto.InternalMessageInfo

func (m *AuthenticateStart) GetMechName() string {
	if m != nil && m.MechName != nil {
		return *m.MechName
	}
	return ""
}

func (m *AuthenticateStart) GetAuthData() []byte {
	if m != nil {
		return m.AuthData
	}
	return nil
}

func (m *AuthenticateStart) GetInitialResponse() []byte {
	if m != nil {
		return m.InitialResponse
	}
	return nil
}

// send by client or server after a :protobuf:msg:`Mysqlx.Session::AuthenticateStart` to
// exchange more auth data
//
// :param auth_data: authentication data
// :Returns: :protobuf:msg:`Mysqlx.Session::AuthenticateContinue`
type AuthenticateContinue struct {
	AuthData             []byte   `protobuf:"bytes,1,req,name=auth_data,json=authData" json:"auth_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateContinue) Reset()         { *m = AuthenticateContinue{} }
func (m *AuthenticateContinue) String() string { return proto.CompactTextString(m) }
func (*AuthenticateContinue) ProtoMessage()    {}
func (*AuthenticateContinue) Descriptor() ([]byte, []int) {
	return fileDescriptor_mysqlx_session_47565295436dd474, []int{1}
}
func (m *AuthenticateContinue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateContinue.Unmarshal(m, b)
}
func (m *AuthenticateContinue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateContinue.Marshal(b, m, deterministic)
}
func (dst *AuthenticateContinue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateContinue.Merge(dst, src)
}
func (m *AuthenticateContinue) XXX_Size() int {
	return xxx_messageInfo_AuthenticateContinue.Size(m)
}
func (m *AuthenticateContinue) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateContinue.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateContinue proto.InternalMessageInfo

func (m *AuthenticateContinue) GetAuthData() []byte {
	if m != nil {
		return m.AuthData
	}
	return nil
}

// sent by the server after successful authentication
//
// :param auth_data: authentication data
type AuthenticateOk struct {
	AuthData             []byte   `protobuf:"bytes,1,opt,name=auth_data,json=authData" json:"auth_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateOk) Reset()         { *m = AuthenticateOk{} }
func (m *AuthenticateOk) String() string { return proto.CompactTextString(m) }
func (*AuthenticateOk) ProtoMessage()    {}
func (*AuthenticateOk) Descriptor() ([]byte, []int) {
	return fileDescriptor_mysqlx_session_47565295436dd474, []int{2}
}
func (m *AuthenticateOk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateOk.Unmarshal(m, b)
}
func (m *AuthenticateOk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateOk.Marshal(b, m, deterministic)
}
func (dst *AuthenticateOk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateOk.Merge(dst, src)
}
func (m *AuthenticateOk) XXX_Size() int {
	return xxx_messageInfo_AuthenticateOk.Size(m)
}
func (m *AuthenticateOk) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateOk.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateOk proto.InternalMessageInfo

func (m *AuthenticateOk) GetAuthData() []byte {
	if m != nil {
		return m.AuthData
	}
	return nil
}

// reset the current session
// param keep_open: if is true the session will be reset, but stays authenticated.
//       otherwise, the session will be closed and needs to be authenticated again.
//
// :Returns: :protobuf:msg:`Mysqlx::Ok`
type Reset struct {
	KeepOpen             *bool    `protobuf:"varint,1,opt,name=keep_open,json=keepOpen,def=0" json:"keep_open,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reset) Reset()         { *m = Reset{} }
func (m *Reset) String() string { return proto.CompactTextString(m) }
func (*Reset) ProtoMessage()    {}
func (*Reset) Descriptor() ([]byte, []int) {
	return fileDescriptor_mysqlx_session_47565295436dd474, []int{3}
}
func (m *Reset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reset.Unmarshal(m, b)
}
func (m *Reset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reset.Marshal(b, m, deterministic)
}
func (dst *Reset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reset.Merge(dst, src)
}
func (m *Reset) XXX_Size() int {
	return xxx_messageInfo_Reset.Size(m)
}
func (m *Reset) XXX_DiscardUnknown() {
	xxx_messageInfo_Reset.DiscardUnknown(m)
}

var xxx_messageInfo_Reset proto.InternalMessageInfo

const Default_Reset_KeepOpen bool = false

func (m *Reset) GetKeepOpen() bool {
	if m != nil && m.KeepOpen != nil {
		return *m.KeepOpen
	}
	return Default_Reset_KeepOpen
}

// close the current session
//
// :Returns: :protobuf:msg:`Mysqlx::Ok`
type Close struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Close) Reset()         { *m = Close{} }
func (m *Close) String() string { return proto.CompactTextString(m) }
func (*Close) ProtoMessage()    {}
func (*Close) Descriptor() ([]byte, []int) {
	return fileDescriptor_mysqlx_session_47565295436dd474, []int{4}
}
func (m *Close) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Close.Unmarshal(m, b)
}
func (m *Close) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Close.Marshal(b, m, deterministic)
}
func (dst *Close) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Close.Merge(dst, src)
}
func (m *Close) XXX_Size() int {
	return xxx_messageInfo_Close.Size(m)
}
func (m *Close) XXX_DiscardUnknown() {
	xxx_messageInfo_Close.DiscardUnknown(m)
}

var xxx_messageInfo_Close proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AuthenticateStart)(nil), "Mysqlx.Session.AuthenticateStart")
	proto.RegisterType((*AuthenticateContinue)(nil), "Mysqlx.Session.AuthenticateContinue")
	proto.RegisterType((*AuthenticateOk)(nil), "Mysqlx.Session.AuthenticateOk")
	proto.RegisterType((*Reset)(nil), "Mysqlx.Session.Reset")
	proto.RegisterType((*Close)(nil), "Mysqlx.Session.Close")
}

func init() {
	proto.RegisterFile("mysqlx_session.proto", fileDescriptor_mysqlx_session_47565295436dd474)
}

var fileDescriptor_mysqlx_session_47565295436dd474 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0xd3, 0x16, 0x14, 0x36, 0xb5, 0x2a, 0x69, 0x22, 0xea, 0xa5, 0xe1, 0x54, 0x2f, 0x04,
	0xe3, 0x8d, 0xc4, 0x83, 0xd6, 0xab, 0x36, 0xa1, 0x0f, 0x40, 0x46, 0x9c, 0x86, 0xb5, 0xb0, 0x8b,
	0xec, 0x90, 0xe8, 0xc5, 0x73, 0x8f, 0x7d, 0x4e, 0x9e, 0xc2, 0xec, 0xc2, 0x01, 0x7b, 0xfd, 0xe6,
	0x9f, 0xfc, 0x5f, 0x7e, 0x36, 0x2f, 0x7f, 0xd4, 0x57, 0xf1, 0x9d, 0x2a, 0x54, 0x8a, 0x4b, 0x11,
	0x56, 0xb5, 0x24, 0xe9, 0xcd, 0x5e, 0x0d, 0x0d, 0x37, 0x1d, 0xbd, 0x99, 0x76, 0xa9, 0xee, 0x1a,
	0xfc, 0xb2, 0xcb, 0xa7, 0x86, 0x72, 0x14, 0xc4, 0x33, 0x20, 0xdc, 0x10, 0xd4, 0xe4, 0xdd, 0x32,
	0xb7, 0xc4, 0x2c, 0x4f, 0x05, 0x94, 0xe8, 0x8f, 0x16, 0xe3, 0xa5, 0x9b, 0x38, 0x1a, 0xbc, 0x41,
	0x89, 0xfa, 0x08, 0x0d, 0xe5, 0xe9, 0x07, 0x10, 0xf8, 0xe3, 0xc5, 0x68, 0x39, 0x4d, 0x1c, 0x0d,
	0x5e, 0x80, 0xc0, 0xbb, 0x63, 0x17, 0x5c, 0x70, 0xe2, 0x50, 0xa4, 0x35, 0xaa, 0x4a, 0x0a, 0x85,
	0xfe, 0xc4, 0x64, 0xce, 0x7b, 0x9e, 0xf4, 0x38, 0xb6, 0xf6, 0x6d, 0x64, 0x05, 0x8f, 0x6c, 0x3e,
	0xec, 0x5f, 0x49, 0x41, 0x5c, 0x34, 0x47, 0x2d, 0x5a, 0x61, 0xd0, 0x12, 0x3b, 0xfb, 0x36, 0xb2,
	0x0f, 0x6d, 0x34, 0x09, 0x1e, 0xd8, 0x6c, 0xf8, 0xbe, 0xde, 0x1d, 0x3f, 0xfe, 0xd3, 0x8b, 0xad,
	0x83, 0xee, 0xbc, 0x67, 0x76, 0x82, 0x0a, 0xc9, 0x0b, 0x98, 0xbb, 0x43, 0xac, 0x52, 0x59, 0xa1,
	0x30, 0x59, 0x27, 0xb6, 0xb7, 0x50, 0x28, 0x4c, 0x1c, 0xcd, 0xd7, 0x15, 0x0a, 0xa3, 0x79, 0x12,
	0x9c, 0x31, 0x7b, 0x55, 0xc8, 0xde, 0xfa, 0xf4, 0xf9, 0x9a, 0x5d, 0x65, 0xb2, 0x0c, 0xcd, 0x92,
	0x61, 0xf6, 0x19, 0xf6, 0x6b, 0xbe, 0x37, 0xdb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x39, 0x1f,
	0x4c, 0xb8, 0x85, 0x01, 0x00, 0x00,
}
